name: news_api
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  dio:
  hexcolor:
  json_annotation:
  cached_network_image: ^3.2.0
  intl:
  eva_icons_flutter: ^3.0.2
  webview_flutter: ^3.0.0
  lottie: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  json_serializable: 

flutter:


  uses-material-design: true

  assets:
    - assets/lottie/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins Semi Bold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf


        